### ISSUE TITLE
TypeError while running kirimase generate

### ISSUE THREAD

**Issue by jiggajoe** [nicoalbanese/kirimase#23]
I get this error when running generate. 

(main⚡) » kirimase generate           
ℹ Quickly generate your Model (Drizzle schema + queries / mutations), Controllers (API Routes and TRPC Routes), and Views                                                          12:40:26 AM
? Please select the resources you would like to generate: Model, TRPC Route, Views + Components (with Shadcn UI, requires TRPC route)
? Please enter the table name (plural and in snake_case): drills
file:///usr/local/lib/node_modules/kirimase/node_modules/@inquirer/core/dist/esm/lib/use-prefix.mjs:17
        const frame = tick % spinner.frames.length;
                                     ^

TypeError: Cannot read properties of undefined (reading 'frames')
    at usePrefix (file:///usr/local/lib/node_modules/kirimase/node_modules/@inquirer/core/dist/esm/lib/use-prefix.mjs:17:38)
    at file:///usr/local/lib/node_modules/kirimase/node_modules/@inquirer/input/dist/esm/index.mjs:9:20
    at workLoop (file:///usr/local/lib/node_modules/kirimase/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:74:42)
    at store.handleChange (file:///usr/local/lib/node_modules/kirimase/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:72:48)
    at ReadStream.wrapped (file:///usr/local/lib/node_modules/kirimase/node_modules/@inquirer/core/dist/esm/lib/hook-engine.mjs:43:13)
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at ReadStream.bound (node:async_hooks:235:16)
    at ReadStream.emit (node:events:525:35)
    at emitKeys (node:internal/readline/utils:357:14)
    at emitKeys.next (<anonymous>)

**Comment by nicoalbanese** [comment]
Hey! I haven't come across this issue before but I'm thinking it's to do with the package not being installed properly. Can you try running the same command but with your package manager of choice prefaced? 
ie npx kirimase@latest generate or pnpm dlx kirimase@latest generate?

**Comment by jiggajoe** [comment]
Thank you so much Nico. That resolved the issue I had!
