### ISSUE TITLE
Failed to initialize Shadcn: ENOENT: no such file or directory, open 'src/app/layout.tsx'

### ISSUE THREAD

**Issue by mcapodici** [nicoalbanese/kirimase#63]
This is what I did to get the error: (Windows 11, node 18.3)

```
marti@Capo MINGW64 /c/data/martin/programming/kirimase-test      
$ npm i -g kirimase

changed 61 packages, and audited 63 packages in 4s

found 0 vulnerabilities

marti@Capo MINGW64 /c/data/martin/programming/kirimase-test      
$ kirimase init
? Are you using a 'src' folder? Yes
? Please pick your preferred package manager NPM
[8:37:50 pm] ✔ File created at ./kirimase.config.json
[8:37:51 pm] ✔ Kirimase initialized!
[8:37:51 pm] ℹ You can now add packages.
? Select a component library to use: Shadcn UI
[8:37:53 pm] ◐ Installing Shadcn UI...
[8:37:53 pm] ◐ Installing packages: tailwindcss-animate class-variance-authority clsx tailwind-merge lucide-react next-themes ... 

added 105 packages, and audited 106 packages in 48s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[8:38:43 pm] ✔ Packages installed: tailwindcss-animate class-variance-authority clsx tailwind-merge lucide-react next-themes 
[8:38:43 pm] ✔ File created at tailwind.config.js
[8:38:43 pm] ✔ File replaced at src/app/globals.css
[8:38:43 pm] ✔ File created at src/lib/utils.ts
[8:38:43 pm] ✔ File created at components.json
[8:38:43 pm] ✔ File created at src/components/ThemeProvider.tsx  
[8:38:43 pm] ✔ File created at src/components/ui/ThemeToggle.tsx 

[8:38:43 pm]  ERROR  Failed to initialize Shadcn: ENOENT: no such file or directory, open 'src/app/layout.tsx'

[8:38:43 pm] ◐ Installing shadcn-ui components: button, toast, avatar, dropdown-menu
Need to install the following packages:
  shadcn-ui@0.4.1
ropdown-menu

node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'src/app/layout.tsx'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at addContextProviderToLayout (file:///C:/Users/marti/AppData/Roaming/nvm/v18.13.0/node_modules/kirimase/dist/commands/add/utils.js:23:28)
    at installShadcnUI (file:///C:/Users/marti/AppData/Roaming/nvm/v18.13.0/node_modules/kirimase/dist/commands/add/componentLib/shadcn-ui/index.js:65:5) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async addPackage (file:///C:/Users/marti/AppData/Roaming/nvm/v18.13.0/node_modules/kirimase/dist/commands/add/index.js:26:17) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'src/app/layout.tsx'
}

Node.js v18.13.0

marti@Capo MINGW64 /c/data/martin/programming/kirimase-test
$ Failed to initialize Shadcn: ENOENT: no such file or directory, open 'src/app/layout.tsx'


```

**Comment by nicoalbanese** [comment]
Hey @mcapodici - are you running Kirimase within a directory that already has a nextjs app?

**Comment by mcapodici** [comment]
No it was an empty folder

**Comment by nicoalbanese** [comment]
Ok - you need to run the cli within a directory that already has a nextjs app. I've put this in the readme but know it's not super visible. Will work on a solution in coming weeks that will flag this during the init script. Cheers!

**Comment by mcapodici** [comment]
Thanks Nico for the fast response. Maybe the script can check? Happy to do a PR or something to help on that.
